apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

# as we are using the docker-desktop's local k8 cluster the PersistentVolume(PV) will be created by the deafult StorageClass, we just need to create the PersistentVolumeClaim(PVC)